apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.existingSecret }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.database.username | quote }}
  password: {{ .Values.database.password | quote }}
  host: {{ .Values.database.hostname | quote }}
  database: {{ .Values.database.database | quote }}
  # the complete JDBC URL
  jdbc-url: "jdbc:postgresql://{{ .Values.database.hostname }}:{{ .Values.database.port }}/{{ .Values.database.database }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ .Values.auth.adminPassword | quote }}